// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Model;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(ProductContext))]
    partial class ProductContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("WebAPI.Model.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            IsActive = false,
                            Price = 7500m,
                            ProductName = "Deneme 1"
                        },
                        new
                        {
                            ProductId = 2,
                            IsActive = true,
                            Price = 8500m,
                            ProductName = "Deneme 2"
                        },
                        new
                        {
                            ProductId = 3,
                            IsActive = true,
                            Price = 8500m,
                            ProductName = "Deneme 3"
                        },
                        new
                        {
                            ProductId = 4,
                            IsActive = false,
                            Price = 10500m,
                            ProductName = "Deneme 4"
                        },
                        new
                        {
                            ProductId = 5,
                            IsActive = true,
                            Price = 11500m,
                            ProductName = "Deneme 5"
                        },
                        new
                        {
                            ProductId = 6,
                            IsActive = true,
                            Price = 12500m,
                            ProductName = "Deneme 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
